### ISSUE TITLE
Unable to run Speed Optimize Manager

### ISSUE THREAD

**Issue by seanbperiod** [thilong/GameGemPackages#1]
Trying to run the new Gamegem on iPhone 5 with 9.0.2 but I'm unable to get the Speed Optimize Manager to run. 

"Error Load speed optimizer configuration. The network connection was lost"

Rolling back to older version in the meantime.

**Comment by asiatiki** [comment]
Same issue here. Running 9.3.3

**Comment by s2rdin** [comment]
Hey Sean mine finds the values I'm looking for but doesn't modify them at all. How do I roll back to the previous version?

**Comment by seanbperiod** [comment]
@s2rdin I tried installing 5 older versions listed on here, and couldn't find the version that had the speedhack working. Not sure if the older versions posted here were modified to have the speedhack removed. @thilong Can you please look into why the speed hack isn't working for our devices?

**Comment by s2rdin** [comment]
Where do I find those versions? I tried to downgrade through cydia but I don't think any older versions are hosted on bigbossrepo. I just need to get back to the (yellow) gamegem that actually worked.

**Comment by seanbperiod** [comment]
they are on this site. https://github.com/thilong/GameGemPackages

**Comment by s2rdin** [comment]
Can't find older versions because I'm running iOS 8.4 and my safari doesn't support it. :/

**Comment by s2rdin** [comment]
But let's say I find the 1.4 version how do I install it on cydia ?

**Comment by seanbperiod** [comment]
Google "How to install deb jailbreak ios"

**Comment by s2rdin** [comment]
I tried several ways to install the older versions but it was a total failure, tried ifliza, Ifile, cydia impactor, funbox etc etc until it occurred to me to make my own cydia repo. So I uploaded the 1.1 version listed on the link you sent me and boom speed optimizer back! Never again upgrading this app! There is almost 0 support from the developer.

**Comment by iPhoneSEhacks** [comment]
Do you have the link or repo for version 1.1?

**Comment by seanbperiod** [comment]
@iPhoneSEhacks click on repo and download the deb there.

**Comment by thamer707** [comment]
After update does not work with ios9.3.3 release. How can i refer to the yellow device

**Comment by thamer707** [comment]
Hi speed tool to work on ios9.3.3 for iPhone 5s. How can i go back to the yellow version. Note that the problem can not connect to the Internet
