### ISSUE TITLE
0 matches

### ISSUE THREAD

**Issue by Astro-Snipes** [thilong/GameGemPackages#15]
still hasn’t been fixed.

**Comment by Piers101** [comment]
Same problem here. Tried fixing with NewTerm 2 but no luck now it just buffers with still 0 results. When will this be fixed?

**Comment by Astro-Snipes** [comment]
When it buffers, switch to newterm and then go back to gamegem and it should start working. Do that when ever it buffers. It doesn’t show 0 results for me but everything I’ve tried it with doesn’t work (snapchat, nfs no limits, simcity buildit, and clash of clans). I’m going to close this issue soon now that I figured it out.

**Comment by Piers101** [comment]
@astro-snipes I’ve done this and it worked however now it shows results but I don’t have the option to select any of them.

**Comment by Thum2488** [comment]
-.-

**Comment by Astro-Snipes** [comment]
The person here explains it pretty well, and has a video how to use it if I do a bad job doing it, https://iosgods.com/topic/73071-temporary-fix-for-gamegem-v15-0-matches-issue/ 
(Make sure you keep it at “any” and “accurate” on game gem) 
when it shows the results the first time, go back to the game/app and change the value of the number you want to change (for nfs you would buy something with the gold or the currency on there, on snapchat you would send a snap to someone to change the snapscore). 
When it changes, put the new number in gamegem and search again, I don’t know how it works but it narrows down the results. 
If the results are below 100 you should be able to view them. If it’s still too high, change the value and do everything I explained one more time, and it should be enough to narrow it down to a couple results.
