### ISSUE TITLE
0 Result

### ISSUE THREAD

**Issue by SadNess1706** [thilong/GameGemPackages#4]
I'm using iOS 11.3.1, Electra latest version.
GameGem 1.5, Everytime I trying to cheat the Infinity Blade 3, I got 0 matches, sometime it say config error, sometime internet error. Can we get a new update please?

**Comment by slimreaper23** [comment]
Did you fix it ?

**Comment by SadNess1706** [comment]
Yes

**Comment by Lynicaldev1** [comment]
How did you fix it? I want to know

**Comment by SadNess1706** [comment]
https://iosgods.com/topic/73071-temporary-fix-for-gamegem-v15-0-matches-issue/
